Repository BioTechCo/main_project, pull requests merged in 2024-08, with the labels that each got.

#51 Fix typo in the pr template
  .github/PULL_REQUEST_TEMPLATE/dev.md
Labels: documentation, enhancement, minor

#48 Ignore dirs at any depth
  .gitignore
Labels: enhancement, urgent, minor

#34 Remove outdated file
  result/result_max_per_gene_single_train.csv
Labels: feature, minor

#52 [Update] dbeta threshold
  poetry.lock
  process/set_dbeta_threshold.ipynb
  pyproject.toml
Labels: minor

#47 Process opt0
  process/split_dataset.ipynb
Labels: help wanted, feature

#59 [Add] filter hyper and TSS
  process/set_dbeta_threshold.ipynb
Labels: feature

#58 [Add] feature name of train and test dataset
  process/split_dataset.ipynb
Labels: enhancement

#69 [update] ignore all files start with all_beta_normalized
  .gitignore
Labels: minor

#70 [Remove] hyper/hypo
  process/set_dbeta_threshold.ipynb
Labels: bug
