Repository BioTechCo/main_project, pull requests merged in 2024-09, with the labels that each got.

#73 [Add] combination validation process
  breast/ml/combination_val.ipynb
Labels: feature

#71 [Add] final combination predict process
  breast/ml/combination_testing.ipynb
Labels: enhancement

#79 Add ID columns in clustering output
  breast/result/GDC_breast_tissue_450k/train80/dbeta_GSE243529_TSS_0.15_consensus.csv
  breast/result/GDC_breast_tissue_450k/train80/dbeta_GSE243529_TSS_0.15_simple.csv
  breast/result/GDC_breast_tissue_450k/train80/dbeta_GSE243529_TSS_0.15_weighted.csv
  process/GO_cluster.ipynb
Labels: feature

#81 [Update] filter overfitting combination and overfitting threshold
  breast/ml/combination_testing.ipynb
  breast/ml/combination_val.ipynb
Labels: bug
